name: gcc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set execute permissions
      run: chmod +x ./scripts/install-ci-linux.sh
    - name: Install dependencies
      run: ./scripts/install-ci-linux.sh
    - name: make clean
      run: make clean
    - name: make
      run: make

